variables:
  DATABASE_URL: "postgres://postgres@postgres/my_database"
  SECRET: "shhhh"

before_script:
  - apt-get update -y
  - apt-get install default-jre -y
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod a+x lein
  - export LEIN_ROOT=1
  - PATH=$PATH:.
  - lein deps

test:
  script:
    - lein test

deploy_staging:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y rubygems
    - gem install dpl
    - dpl --provider=heroku --app=bog-stg --api-key=$HEROKU_API_KEY
  only:
    - master

deploy_production:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y rubygems
    - gem install dpl
    - dpl --provider=heroku --app=bog-prod --api-key=$HEROKU_API_KEY
  only:
    - tags
